#!/usr/bin/env python
from pyres.scheduler import Scheduler
def main():
    from optparse import OptionParser
    usage = "usage: %prog [options] arg1"
    parser = OptionParser(usage=usage)
    #parser.add_option("-q", dest="queue_list")
    parser.add_option("--host", dest="host", default="localhost")
    parser.add_option("--port",dest="port",type="int", default=6379)
    (options,args) = parser.parse_args()
    server = '%s:%s' % (options.host,options.port)
    Scheduler.run(server)

if __name__ == "__main__":
    main()