#!/usr/bin/env python
from resweb import server
from itty import *
def main():
    from optparse import OptionParser
    usage = "usage: %prog [options]"
    parser = OptionParser(usage)
    parser.add_option("--host",
                    dest="host",
                    default="localhost",
                    metavar="HOST")
    parser.add_option("--port",
                    dest="port",
                    type="int", 
                    default=8080)
    (options,args) = parser.parse_args()
    run_itty(host=options.host, port=options.port)

if __name__ == "__main__":
    main()